QUESTIONS = [
    {
        "id": 1,
        "question": "An e-commerce company wants to predict whether a user will buy in this session (Yes/No). Which ML approach fits best?",
        "options": ["Regression", "Binary Classification", "Clustering", "Association Rules"],
        "answer": "Binary Classification",
    },
    {
        "id": 2,
        "question": "A delivery startup wants to estimate delivery time in minutes for each order. Which model family should be selected first?",
        "options": ["Regression", "Classification", "Clustering", "Dimensionality Reduction"],
        "answer": "Regression",
    },
    {
        "id": 3,
        "question": "A telecom team has unlabeled customer usage behavior and wants to create customer segments for campaigns. What should they use?",
        "options": ["Logistic Regression", "Random Forest Classifier", "K-Means Clustering", "Linear Regression"],
        "answer": "K-Means Clustering",
    },
    {
        "id": 4,
        "question": "In EDA, churn rate appears heavily different across contract types. What is the best immediate next step?",
        "options": ["Drop contract type", "Validate and include it as a key feature", "Shuffle target labels", "Scale only target"],
        "answer": "Validate and include it as a key feature",
    },
    {
        "id": 5,
        "question": "You see customer_id and full_name columns in a fraud prediction dataset. What should be done before training?",
        "options": ["Keep both as is", "Use only full_name", "Remove high-cardinality identifiers", "Convert both to target"],
        "answer": "Remove high-cardinality identifiers",
    },
    {
        "id": 6,
        "question": "House prices are right-skewed in EDA. Which transformation is commonly useful for the target?",
        "options": ["One-hot encoding", "Log transform", "Label encoding", "Min-max scale target to 0/1 only"],
        "answer": "Log transform",
    },
    {
        "id": 7,
        "question": "You must explain predictions to banking auditors. Which model is a strong baseline choice?",
        "options": ["Deep Neural Network", "Logistic Regression", "K-Means", "XGBoost with no explainability"],
        "answer": "Logistic Regression",
    },
    {
        "id": 8,
        "question": "A support team wants to route tickets into 6 known categories. Which approach is appropriate?",
        "options": ["Multiclass Classification", "Regression", "Clustering only", "Time-series forecasting"],
        "answer": "Multiclass Classification",
    },
    {
        "id": 9,
        "question": "Your EDA shows 2% fraud and 98% non-fraud. Which metric should be prioritized over accuracy?",
        "options": ["MAE", "R-squared", "F1-score", "Explained variance"],
        "answer": "F1-score",
    },
    {
        "id": 10,
        "question": "A retailer wants weekly demand forecasts per store with date-based trends. Which modeling setup is most suitable?",
        "options": ["Image classification", "Time-series forecasting", "K-Means segmentation", "Topic modeling"],
        "answer": "Time-series forecasting",
    },
    {
        "id": 11,
        "question": "In a loan dataset, income has 12% missing values. What is a reasonable first treatment?",
        "options": ["Drop all rows with income missing immediately", "Impute with median/strategy after analysis", "Fill with random values", "Use test set values for imputation"],
        "answer": "Impute with median/strategy after analysis",
    },
    {
        "id": 12,
        "question": "A model uses KNN with features like salary (0-1,000,000) and age (18-70). What preprocessing is essential?",
        "options": ["No preprocessing needed", "Feature scaling", "Only target encoding", "Drop salary feature"],
        "answer": "Feature scaling",
    },
    {
        "id": 13,
        "question": "The column city has categories without natural order. Which encoding is safer?",
        "options": ["Label encoding with arbitrary order", "One-hot encoding", "Leave as plain string", "Convert to float directly"],
        "answer": "One-hot encoding",
    },
    {
        "id": 14,
        "question": "You detect duplicate transactions during cleaning. What should be done?",
        "options": ["Keep duplicates always", "Investigate and remove true duplicates", "Replace duplicates with null", "Move duplicates to test set"],
        "answer": "Investigate and remove true duplicates",
    },
    {
        "id": 15,
        "question": "A feature signup_date is text. You need model-ready features. What is best?",
        "options": ["Drop date always", "Extract meaningful date parts (month, weekday, etc.)", "Use it unchanged", "Convert all dates to target"],
        "answer": "Extract meaningful date parts (month, weekday, etc.)",
    },
    {
        "id": 16,
        "question": "When should outliers be removed automatically?",
        "options": ["Always, without checking", "Only after validating they are errors or harmful for objective", "Never", "Only from test set"],
        "answer": "Only after validating they are errors or harmful for objective",
    },
    {
        "id": 17,
        "question": "Train and test were scaled separately using different fit parameters. What issue does this create?",
        "options": ["Better generalization", "Inconsistent feature space and unreliable predictions", "Faster inference", "No impact at all"],
        "answer": "Inconsistent feature space and unreliable predictions",
    },
    {
        "id": 18,
        "question": "A column has 85% missing values and weak business relevance. What is often a practical choice?",
        "options": ["Force fill with zeros", "Drop the feature after validation", "Use it as target", "Duplicate rows"],
        "answer": "Drop the feature after validation",
    },
    {
        "id": 19,
        "question": "You applied target leakage by creating a feature from post-outcome data. What should be done?",
        "options": ["Keep it for higher accuracy", "Remove leakage feature and retrain", "Use only leakage feature", "Move it to labels"],
        "answer": "Remove leakage feature and retrain",
    },
    {
        "id": 20,
        "question": "A fraud rule-based feature and model score from previous system are available. Best approach?",
        "options": ["Ignore both", "Evaluate as engineered features with leakage checks", "Use score as target", "Randomly drop one"],
        "answer": "Evaluate as engineered features with leakage checks",
    },
    {
        "id": 21,
        "question": "For standard supervised ML, what split is commonly used first?",
        "options": ["100-0", "80-20 or 70-30", "10-90", "No split needed"],
        "answer": "80-20 or 70-30",
    },
    {
        "id": 22,
        "question": "In churn prediction with class imbalance, which split strategy is preferred?",
        "options": ["Random without class control", "Stratified train-test split", "Split by alphabetical order", "Use only train set"],
        "answer": "Stratified train-test split",
    },
    {
        "id": 23,
        "question": "Sales forecasting data spans Jan 2021 to Dec 2025. How should split be done?",
        "options": ["Randomly shuffle and split", "Chronological split by time", "Cluster-based split", "No validation"],
        "answer": "Chronological split by time",
    },
    {
        "id": 24,
        "question": "You performed scaling before train-test split. What risk appears?",
        "options": ["Data leakage", "Class imbalance reduction", "Guaranteed better recall", "No risk"],
        "answer": "Data leakage",
    },
    {
        "id": 25,
        "question": "A small dataset gives unstable single-split performance. What should you use?",
        "options": ["Cross-validation", "Only holdout once", "No testing", "Only training accuracy"],
        "answer": "Cross-validation",
    },
    {
        "id": 26,
        "question": "Train accuracy is 97% and test accuracy is 61%. What is likely happening?",
        "options": ["Underfitting", "Overfitting", "Perfect fit", "Data is clean"],
        "answer": "Overfitting",
    },
    {
        "id": 27,
        "question": "Why keep random_state fixed during experiments?",
        "options": ["To increase model complexity", "To ensure reproducibility", "To remove missing values", "To avoid feature engineering"],
        "answer": "To ensure reproducibility",
    },
    {
        "id": 28,
        "question": "When should test data be used in the workflow?",
        "options": ["For hyperparameter tuning repeatedly", "For final unbiased evaluation", "For feature scaling fit", "For oversampling training"],
        "answer": "For final unbiased evaluation",
    },
    {
        "id": 29,
        "question": "Your validation score and test score are very close. What does it indicate?",
        "options": ["Strong leakage", "Model instability", "Reasonable generalization", "Always underfitting"],
        "answer": "Reasonable generalization",
    },
    {
        "id": 30,
        "question": "For patient-level medical records, same patient appears multiple times. How should split be designed?",
        "options": ["Allow same patient in train and test", "Group-aware split by patient", "Split by row index only", "Use only one patient"],
        "answer": "Group-aware split by patient",
    },
    {
        "id": 31,
        "question": "A marketing team asks: Who will click ad? Which model type should start the baseline?",
        "options": ["Logistic Regression classifier", "Linear Regression", "K-Means only", "PCA only"],
        "answer": "Logistic Regression classifier",
    },
    {
        "id": 32,
        "question": "A dataset has many nonlinear feature interactions and mixed types. Which model is a strong candidate?",
        "options": ["Decision Tree/Random Forest", "Naive average only", "PCA as final predictor", "K-Means as classifier"],
        "answer": "Decision Tree/Random Forest",
    },
    {
        "id": 33,
        "question": "For imbalanced fraud detection, what trade-off is commonly tuned?",
        "options": ["Precision vs Recall threshold", "MSE vs RMSE", "Rows vs columns", "CPU vs RAM only"],
        "answer": "Precision vs Recall threshold",
    },
    {
        "id": 34,
        "question": "If false negatives are very costly (missing fraud), which metric should get priority?",
        "options": ["Recall", "Specificity only", "R-squared", "MAPE"],
        "answer": "Recall",
    },
    {
        "id": 35,
        "question": "For regression of claim amount, which metric is valid?",
        "options": ["F1-score", "MSE or MAE", "ROC-AUC", "Confusion Matrix"],
        "answer": "MSE or MAE",
    },
    {
        "id": 36,
        "question": "AUC-ROC is most appropriate for:",
        "options": ["Binary classification ranking quality", "Linear regression only", "Clustering inertia", "Feature scaling quality"],
        "answer": "Binary classification ranking quality",
    },
    {
        "id": 37,
        "question": "You compare baseline and tuned model. Which process is correct?",
        "options": ["Pick tuned model only by train score", "Compare on validation/test and business metric", "Choose model with most features", "Pick newest algorithm always"],
        "answer": "Compare on validation/test and business metric",
    },
    {
        "id": 38,
        "question": "A model has slightly lower accuracy but much higher recall for fraud. Decision depends on:",
        "options": ["UI color theme", "Business cost of false negatives", "Number of developers", "Random seed alone"],
        "answer": "Business cost of false negatives",
    },
    {
        "id": 39,
        "question": "Feature importance shows one variable dominates predictions unexpectedly. Best next step?",
        "options": ["Ignore and deploy", "Audit for leakage/data quality issue", "Drop all other features", "Shuffle labels"],
        "answer": "Audit for leakage/data quality issue",
    },
    {
        "id": 40,
        "question": "Calibration is important when:",
        "options": ["You need reliable probability estimates", "You only need clustering", "Target is text generation", "There is no test set"],
        "answer": "You need reliable probability estimates",
    },
    {
        "id": 41,
        "question": "After training, you need to save the model for reuse in API. Which is common in Python ML?",
        "options": ["Save as PNG", "Pickle or joblib serialization", "Store only in browser cache", "Screenshot model output"],
        "answer": "Pickle or joblib serialization",
    },
    {
        "id": 42,
        "question": "Why should preprocessing objects (encoder/scaler) be saved with model artifact?",
        "options": ["Only for documentation", "To ensure same transformations in inference", "To increase training data", "To reduce label count"],
        "answer": "To ensure same transformations in inference",
    },
    {
        "id": 43,
        "question": "Model works in notebook but fails in production due to category mismatch. What was likely missed?",
        "options": ["GPU upgrade", "Consistent preprocessing pipeline packaging", "Lower learning rate", "More epochs only"],
        "answer": "Consistent preprocessing pipeline packaging",
    },
    {
        "id": 44,
        "question": "You receive new data with shifted behavior months later. What should monitoring detect?",
        "options": ["Only API uptime", "Data drift and performance drift", "Just model file size", "Color scheme drift"],
        "answer": "Data drift and performance drift",
    },
    {
        "id": 45,
        "question": "What is a good deployment validation before exposing model to all users?",
        "options": ["No validation needed", "Shadow/canary testing with monitoring", "Train on production labels first", "Disable logs"],
        "answer": "Shadow/canary testing with monitoring",
    },
    {
        "id": 46,
        "question": "A pipeline predicts churn. Business asks who is high risk and why. What should be added?",
        "options": ["Only raw probabilities", "Explainability outputs (feature contribution summaries)", "Random comments", "Larger batch size only"],
        "answer": "Explainability outputs (feature contribution summaries)",
    },
    {
        "id": 47,
        "question": "If prediction latency is too high in production, first optimization step is:",
        "options": ["Remove test set", "Profile bottlenecks and simplify pipeline/model", "Increase labels", "Skip preprocessing"],
        "answer": "Profile bottlenecks and simplify pipeline/model",
    },
    {
        "id": 48,
        "question": "You retrain monthly and want reproducible versions. What is essential?",
        "options": ["Version model, data snapshot, and code", "Only version final accuracy", "Only keep newest file", "No metadata needed"],
        "answer": "Version model, data snapshot, and code",
    },
    {
        "id": 49,
        "question": "A pickled model from unknown source is loaded in production. Main risk is:",
        "options": ["Minor formatting issue only", "Security risk from unsafe deserialization", "Higher recall automatically", "No risk if file exists"],
        "answer": "Security risk from unsafe deserialization",
    },
    {
        "id": 50,
        "question": "Final ML project success is best measured by:",
        "options": ["Highest training accuracy only", "Real business impact with reliable production performance", "Largest model size", "Most complex algorithm"],
        "answer": "Real business impact with reliable production performance",
    },
]
