QUESTIONS = [
    {
        "id": 1,
        "question": "[Telecom Table Set] Table: columns=[CustomerID, Age, Tenure, Churn], rows=[[C001,45,12,Yes],[C002,30,24,No]]. The company wants to predict Churn. What type of ML problem is this?",
        "options": ["Regression", "Classification", "Clustering", "Reinforcement Learning"],
        "answer": "Classification",
    },
    {
        "id": 2,
        "question": "Table: columns=[CustomerID, Age, Churn], rows=[[C101,25,Yes],[C102,33,No]]. CustomerID is unique for every row. What should you do?",
        "options": ["Normalize it", "Encode it", "Remove it", "Use it as target"],
        "answer": "Remove it",
    },
    {
        "id": 3,
        "question": "Table: columns=[Gender, ContractType, Churn], rows=[[Male,Month-to-Month,Yes],[Female,One-Year,No]]. What must be done before applying Logistic Regression?",
        "options": ["Nothing", "Encode categorical variables", "Remove them", "Duplicate rows"],
        "answer": "Encode categorical variables",
    },
    {
        "id": 4,
        "question": "Table: columns=[Churn, Count], rows=[[Yes,1300],[No,3700]]. How should this distribution be interpreted?",
        "options": ["Severe imbalance", "Moderate imbalance", "Perfect balance", "Remove minority class"],
        "answer": "Moderate imbalance",
    },
    {
        "id": 5,
        "question": "Table: Actual/Pred matrix -> Yes:[predYes=300,predNo=200], No:[predYes=150,predNo=850]. To reduce false negatives, which metric is important?",
        "options": ["Accuracy", "Precision", "Recall", "MSE"],
        "answer": "Recall",
    },
    {
        "id": 6,
        "question": "Table: Train Accuracy=92%, Test Accuracy=64%. What does this indicate?",
        "options": ["Underfitting", "Overfitting", "Balanced model", "Perfect model"],
        "answer": "Overfitting",
    },
    {
        "id": 7,
        "question": "Table: feature coefficients -> MonthlyCharges=0.6, Tenure=-0.4. Positive coefficient for MonthlyCharges suggests:",
        "options": ["Higher charges increase churn probability", "Higher charges reduce churn", "No impact", "Random noise"],
        "answer": "Higher charges increase churn probability",
    },
    {
        "id": 8,
        "question": "Table: [Age, Tenure, MonthlyCharges] sample rows [[25,5,40],[60,30,100]]. If using KNN, what preprocessing is essential?",
        "options": ["Feature scaling", "Drop tenure", "Remove age", "Encode target"],
        "answer": "Feature scaling",
    },
    {
        "id": 9,
        "question": "Table: Month vs Accuracy -> Jan=82%, Aug=65%. Accuracy drop over time indicates:",
        "options": ["Data drift", "Overfitting", "Scaling issue", "Hardware issue"],
        "answer": "Data drift",
    },
    {
        "id": 10,
        "question": "Table: Before Model churn=26%, After Model churn=20%. What indicates project success?",
        "options": ["Higher test accuracy", "Reduced churn rate", "More features", "Faster training"],
        "answer": "Reduced churn rate",
    },
    {
        "id": 11,
        "question": "Table: [Age, MonthlyCharges, Churn] sample rows [[22,40,No],[58,110,Yes]]. Age is stored as text in raw data. What should be done before training?",
        "options": ["Remove Age", "Convert to numeric", "Encode as category", "Ignore"],
        "answer": "Convert to numeric",
    },
    {
        "id": 12,
        "question": "Table: [Tenure, MonthlyCharges, TotalCharges] with TotalCharges about Tenure*MonthlyCharges. What risk does this create?",
        "options": ["Class imbalance", "Multicollinearity", "Underfitting", "Data leakage"],
        "answer": "Multicollinearity",
    },
    {
        "id": 13,
        "question": "Table: Missing values review. If a column has 40% missing values, what is the first step?",
        "options": ["Immediately drop dataset", "Investigate importance of feature", "Fill with zero blindly", "Duplicate rows"],
        "answer": "Investigate importance of feature",
    },
    {
        "id": 14,
        "question": "Table: Train Size=4000, Test Size=1000. What split ratio is this approximately?",
        "options": ["50-50", "70-30", "80-20", "90-10"],
        "answer": "80-20",
    },
    {
        "id": 15,
        "question": "Table: random_state=42. Why use random_state in train-test split?",
        "options": ["Increase accuracy", "Reproducibility", "Faster training", "Reduce bias"],
        "answer": "Reproducibility",
    },
    {
        "id": 16,
        "question": "Table: Feature scaling applied before split on entire dataset. This may cause:",
        "options": ["Overfitting", "Data leakage", "Class imbalance", "Underfitting"],
        "answer": "Data leakage",
    },
    {
        "id": 17,
        "question": "Table: Actual=Yes, Predicted=No for a row. This is called:",
        "options": ["True Positive", "False Positive", "False Negative", "True Negative"],
        "answer": "False Negative",
    },
    {
        "id": 18,
        "question": "Table: Model comparison -> Logistic Regression=78%, Random Forest=85%. Which model performs better?",
        "options": ["Logistic Regression", "Random Forest", "Both equal", "Cannot decide"],
        "answer": "Random Forest",
    },
    {
        "id": 19,
        "question": "Table: [Tenure, Churn] sample [[2,Yes],[36,No]]. This indicates:",
        "options": ["Tenure is important feature", "Tenure irrelevant", "Data leakage", "Noise"],
        "answer": "Tenure is important feature",
    },
    {
        "id": 20,
        "question": "Table: Model Type vs Needs Scaling -> KNN=Yes, Decision Tree=No. Which model is distance-based?",
        "options": ["Decision Tree", "Random Forest", "KNN", "Naive Bayes"],
        "answer": "KNN",
    },
    {
        "id": 21,
        "question": "Table: Predicted Yes=400, Predicted No=600 with high accuracy but low recall. This indicates:",
        "options": ["Model misses positive cases", "Perfect model", "Balanced data", "No issue"],
        "answer": "Model misses positive cases",
    },
    {
        "id": 22,
        "question": "Table: CV scores [0.78,0.80,0.79,0.77,0.81]. These scores indicate:",
        "options": ["Stable model", "Overfitting", "Underfitting", "Data leakage"],
        "answer": "Stable model",
    },
    {
        "id": 23,
        "question": "Table: Decision Tree Train Acc=99%, Test Acc=60%. Decision Tree is likely:",
        "options": ["Underfitting", "Overfitting", "Balanced", "Perfect"],
        "answer": "Overfitting",
    },
    {
        "id": 24,
        "question": "Table: ContractType churn rates -> Month-to-Month=40%, Two-Year=10%. Which has higher churn risk?",
        "options": ["Two-Year", "Month-to-Month", "Both equal", "Cannot decide"],
        "answer": "Month-to-Month",
    },
    {
        "id": 25,
        "question": "Table: Feature importance -> MonthlyCharges=0.32, Tenure=0.28. Which influences churn more?",
        "options": ["Tenure", "MonthlyCharges", "Equal", "None"],
        "answer": "MonthlyCharges",
    },
    {
        "id": 26,
        "question": "Table: Hyperparameter max_depth=3. Reducing max_depth helps prevent:",
        "options": ["Underfitting", "Overfitting", "Class imbalance", "Leakage"],
        "answer": "Overfitting",
    },
    {
        "id": 27,
        "question": "Table: Churn metrics -> Precision=0.72, Recall=0.65. Recall 0.65 means:",
        "options": ["65% actual churners correctly predicted", "65% total predictions correct", "65% non-churn predicted", "Model accuracy 65%"],
        "answer": "65% actual churners correctly predicted",
    },
    {
        "id": 28,
        "question": "Table: Before deployment accuracy=85%, after deployment=70%. Primary reason:",
        "options": ["Data drift", "Encoding", "Train-test split", "Random state"],
        "answer": "Data drift",
    },
    {
        "id": 29,
        "question": "Table: Model saved as 'pickle file'. Why save model as pickle/joblib?",
        "options": ["Store trained model for reuse", "Increase accuracy", "Reduce data size", "Encode data"],
        "answer": "Store trained model for reuse",
    },
    {
        "id": 30,
        "question": "Table: Deployment tool = Streamlit. Streamlit is mainly used for:",
        "options": ["Model training", "Web app deployment", "Data cleaning", "Encoding"],
        "answer": "Web app deployment",
    },
    {
        "id": 31,
        "question": "Table: Actual Yes=600 (Pred Yes=420, Pred No=180). How many false negatives exist?",
        "options": ["420", "180", "600", "0"],
        "answer": "180",
    },
    {
        "id": 32,
        "question": "Table: Model A(Precision=0.80, Recall=0.60), Model B(Precision=0.70, Recall=0.85). If reducing missed churners is priority, choose:",
        "options": ["Model A", "Model B", "Both equal", "Cannot decide"],
        "answer": "Model B",
    },
    {
        "id": 33,
        "question": "Table: Correlation with churn -> Tenure=-0.52, MonthlyCharges=0.48. Negative correlation for Tenure suggests:",
        "options": ["Higher tenure reduces churn likelihood", "Higher tenure increases churn", "No relationship", "Data leakage"],
        "answer": "Higher tenure reduces churn likelihood",
    },
    {
        "id": 34,
        "question": "Table: Train Accuracy=65%, Test Accuracy=63%. This performance suggests:",
        "options": ["Overfitting", "Underfitting", "Balanced but low performance", "Perfect model"],
        "answer": "Balanced but low performance",
    },
    {
        "id": 35,
        "question": "Table: [Tenure, MonthlyCharges, TotalCharges] where TotalCharges approx Tenure*MonthlyCharges. Including all three may cause:",
        "options": ["Class imbalance", "Multicollinearity", "Over-sampling", "Data drift"],
        "answer": "Multicollinearity",
    },
    {
        "id": 36,
        "question": "Table: Probability scores -> Customer A=0.85, Customer B=0.40. Threshold=0.5. Who is predicted to churn?",
        "options": ["Customer A only", "Customer B only", "Both", "None"],
        "answer": "Customer A only",
    },
    {
        "id": 37,
        "question": "Table: ROC-AUC -> Logistic Regression=0.78, Random Forest=0.88. Which model performs better overall?",
        "options": ["Logistic Regression", "Random Forest", "Both equal", "Cannot compare"],
        "answer": "Random Forest",
    },
    {
        "id": 38,
        "question": "Table: Actual No predicted as Yes count=250. This is called:",
        "options": ["True Positive", "False Positive", "False Negative", "True Negative"],
        "answer": "False Positive",
    },
    {
        "id": 39,
        "question": "Table: CV scores [0.84,0.85,0.83,0.86,0.84]. Low variance indicates:",
        "options": ["Model instability", "Model stability", "Underfitting", "Data leakage"],
        "answer": "Model stability",
    },
    {
        "id": 40,
        "question": "Table: Feature importance -> ContractType=0.40, InternetService=0.15. Which feature influences churn more?",
        "options": ["InternetService", "ContractType", "Equal", "None"],
        "answer": "ContractType",
    },
    {
        "id": 41,
        "question": "Table: Deployment uses model file 'model.pkl'. Why store model as .pkl?",
        "options": ["To retrain faster", "To reuse trained model", "To scale data", "To encode features"],
        "answer": "To reuse trained model",
    },
    {
        "id": 42,
        "question": "Table: Churn rate before=26%, after=18%. Business impact suggests:",
        "options": ["Project failure", "Successful implementation", "Model underfitting", "Data leakage"],
        "answer": "Successful implementation",
    },
    {
        "id": 43,
        "question": "Table: New pricing plan introduced=Yes. New pricing affecting churn distribution may cause:",
        "options": ["Overfitting", "Data drift", "Random noise", "Underfitting"],
        "answer": "Data drift",
    },
    {
        "id": 44,
        "question": "Table: Logistic Regression Train Acc=78%, Test Acc=77%. This model shows:",
        "options": ["Overfitting", "Good generalization", "Underfitting", "Leakage"],
        "answer": "Good generalization",
    },
    {
        "id": 45,
        "question": "Table: Threshold vs Recall -> 0.3=>0.90, 0.7=>0.55. Lowering threshold increases:",
        "options": ["Recall", "Precision", "Accuracy always", "Overfitting"],
        "answer": "Recall",
    },
    {
        "id": 46,
        "question": "Table: Feature scaling applied? KNN=Yes, Decision Tree=No. Which model requires scaling?",
        "options": ["Decision Tree", "Random Forest", "KNN", "None"],
        "answer": "KNN",
    },
    {
        "id": 47,
        "question": "Table: Churn probabilities -> Customer X=0.51, Customer Y=0.49. Threshold=0.5. Who churns?",
        "options": ["Customer X", "Customer Y", "Both", "None"],
        "answer": "Customer X",
    },
    {
        "id": 48,
        "question": "Table: Actual Yes=600, Predicted Yes=480. Recall = PredictedYes/ActualYes. Approx recall?",
        "options": ["0.60", "0.70", "0.80", "0.90"],
        "answer": "0.80",
    },
    {
        "id": 49,
        "question": "Table: Feature added -> Tenure * MonthlyCharges. Creating this new feature is called:",
        "options": ["Encoding", "Feature engineering", "Scaling", "Overfitting"],
        "answer": "Feature engineering",
    },
    {
        "id": 50,
        "question": "Table: Primary Goal -> Reduce churn and increase revenue. Final ML project success depends on:",
        "options": ["Highest accuracy", "Business impact", "Complex model", "More features"],
        "answer": "Business impact",
    },
]
