QUESTIONS = [
    {
        "id": 1,
        "question": "Which algorithm is primarily used for predicting a continuous numeric output?",
        "options": ["Logistic Regression", "Linear Regression", "K-Means Clustering", "Naive Bayes"],
        "answer": "Linear Regression",
    },
    {
        "id": 2,
        "question": "What does the 'bias' term represent in a linear regression model?",
        "options": [
            "The slope of the regression line",
            "The y-intercept of the regression line",
            "The variance of the model",
            "The regularization parameter",
        ],
        "answer": "The y-intercept of the regression line",
    },
    {
        "id": 3,
        "question": "Which evaluation metric is most appropriate for a regression problem?",
        "options": ["Accuracy", "F1 Score", "Mean Squared Error", "AUC-ROC"],
        "answer": "Mean Squared Error",
    },
    {
        "id": 4,
        "question": "Logistic Regression is used for which type of task?",
        "options": ["Regression", "Classification", "Clustering", "Dimensionality Reduction"],
        "answer": "Classification",
    },
    {
        "id": 5,
        "question": "What activation function does Logistic Regression use to output probabilities?",
        "options": ["ReLU", "Tanh", "Sigmoid", "Softmax"],
        "answer": "Sigmoid",
    },
    {
        "id": 6,
        "question": "Which of the following is a supervised learning algorithm?",
        "options": ["K-Means", "DBSCAN", "Random Forest", "PCA"],
        "answer": "Random Forest",
    },
    {
        "id": 7,
        "question": "In Decision Trees, what criterion is commonly used to measure impurity?",
        "options": ["Mean Absolute Error", "Gini Index", "Silhouette Score", "Euclidean Distance"],
        "answer": "Gini Index",
    },
    {
        "id": 8,
        "question": "What problem does overfitting describe in machine learning?",
        "options": [
            "Model performs poorly on training data",
            "Model generalizes well to unseen data",
            "Model memorizes training data and performs poorly on test data",
            "Model has too few parameters",
        ],
        "answer": "Model memorizes training data and performs poorly on test data",
    },
    {
        "id": 9,
        "question": "Which technique helps prevent overfitting in a neural network?",
        "options": ["Increasing learning rate", "Dropout", "Removing hidden layers", "Using larger batches only"],
        "answer": "Dropout",
    },
    {
        "id": 10,
        "question": "What is the purpose of a validation set?",
        "options": [
            "To train the model",
            "To tune hyperparameters and evaluate during training",
            "To deploy the model",
            "To collect more data",
        ],
        "answer": "To tune hyperparameters and evaluate during training",
    },
    {
        "id": 11,
        "question": "Which algorithm works by finding the hyperplane that best separates two classes?",
        "options": ["K-Nearest Neighbors", "Support Vector Machine", "Naive Bayes", "Decision Tree"],
        "answer": "Support Vector Machine",
    },
    {
        "id": 12,
        "question": "In SVM, what are the data points closest to the decision boundary called?",
        "options": ["Outliers", "Centroids", "Support Vectors", "Clusters"],
        "answer": "Support Vectors",
    },
    {
        "id": 13,
        "question": "What does the 'K' in K-Nearest Neighbors represent?",
        "options": [
            "Number of clusters",
            "Number of features",
            "Number of nearest neighbors to consider",
            "Number of iterations",
        ],
        "answer": "Number of nearest neighbors to consider",
    },
    {
        "id": 14,
        "question": "Which distance metric is most commonly used in KNN?",
        "options": ["Manhattan Distance", "Cosine Similarity", "Euclidean Distance", "Hamming Distance"],
        "answer": "Euclidean Distance",
    },
    {
        "id": 15,
        "question": "Naive Bayes classifier is based on which theorem?",
        "options": ["Central Limit Theorem", "Bayes' Theorem", "Pythagorean Theorem", "Law of Large Numbers"],
        "answer": "Bayes' Theorem",
    },
    {
        "id": 16,
        "question": "What assumption does Naive Bayes make about features?",
        "options": [
            "Features are correlated",
            "Features are conditionally independent given the class",
            "Features must be numerical",
            "Features follow a uniform distribution",
        ],
        "answer": "Features are conditionally independent given the class",
    },
    {
        "id": 17,
        "question": "Random Forest is an ensemble of which base learner?",
        "options": ["Linear Regressors", "SVMs", "Decision Trees", "Neural Networks"],
        "answer": "Decision Trees",
    },
    {
        "id": 18,
        "question": "What ensemble technique does Random Forest use?",
        "options": ["Boosting", "Bagging", "Stacking", "Blending"],
        "answer": "Bagging",
    },
    {
        "id": 19,
        "question": "Gradient Boosting builds trees sequentially. What does each new tree try to correct?",
        "options": [
            "The predictions of the first tree only",
            "The residual errors of the previous ensemble",
            "The feature importances",
            "The learning rate",
        ],
        "answer": "The residual errors of the previous ensemble",
    },
    {
        "id": 20,
        "question": "Which of the following is an example of a boosting algorithm?",
        "options": ["Random Forest", "Bagging Classifier", "XGBoost", "K-Means"],
        "answer": "XGBoost",
    },
    {
        "id": 21,
        "question": "What is the main goal of Principal Component Analysis (PCA)?",
        "options": [
            "Classification",
            "Clustering",
            "Dimensionality Reduction",
            "Anomaly Detection",
        ],
        "answer": "Dimensionality Reduction",
    },
    {
        "id": 22,
        "question": "K-Means clustering requires which input parameter?",
        "options": [
            "The number of features",
            "The number of clusters K",
            "The learning rate",
            "The depth of the tree",
        ],
        "answer": "The number of clusters K",
    },
    {
        "id": 23,
        "question": "Which metric measures how well-separated clusters are in K-Means?",
        "options": ["R-squared", "F1 Score", "Silhouette Score", "Log Loss"],
        "answer": "Silhouette Score",
    },
    {
        "id": 24,
        "question": "What type of learning is K-Means clustering?",
        "options": ["Supervised", "Unsupervised", "Semi-supervised", "Reinforcement"],
        "answer": "Unsupervised",
    },
    {
        "id": 25,
        "question": "In a Confusion Matrix, what does 'True Positive' mean?",
        "options": [
            "Model predicts positive and actual is negative",
            "Model predicts negative and actual is positive",
            "Model predicts positive and actual is positive",
            "Model predicts negative and actual is negative",
        ],
        "answer": "Model predicts positive and actual is positive",
    },
    {
        "id": 26,
        "question": "Precision is defined as:",
        "options": [
            "TP / (TP + FN)",
            "TP / (TP + FP)",
            "TN / (TN + FP)",
            "(TP + TN) / Total",
        ],
        "answer": "TP / (TP + FP)",
    },
    {
        "id": 27,
        "question": "Recall (Sensitivity) is defined as:",
        "options": [
            "TP / (TP + FP)",
            "TP / (TP + FN)",
            "TN / (TN + FN)",
            "(TP + TN) / Total",
        ],
        "answer": "TP / (TP + FN)",
    },
    {
        "id": 28,
        "question": "The F1 Score is the harmonic mean of which two metrics?",
        "options": [
            "Accuracy and Recall",
            "Precision and Recall",
            "Precision and Specificity",
            "Accuracy and Precision",
        ],
        "answer": "Precision and Recall",
    },
    {
        "id": 29,
        "question": "AUC-ROC curve plots which two metrics?",
        "options": [
            "Precision vs Recall",
            "True Positive Rate vs False Positive Rate",
            "Accuracy vs Loss",
            "Bias vs Variance",
        ],
        "answer": "True Positive Rate vs False Positive Rate",
    },
    {
        "id": 30,
        "question": "What does regularization do in a machine learning model?",
        "options": [
            "Increases model complexity",
            "Penalizes large coefficients to prevent overfitting",
            "Removes all features",
            "Increases the training data size",
        ],
        "answer": "Penalizes large coefficients to prevent overfitting",
    },
    {
        "id": 31,
        "question": "L1 regularization is also known as:",
        "options": ["Ridge Regression", "Lasso Regression", "Elastic Net", "Polynomial Regression"],
        "answer": "Lasso Regression",
    },
    {
        "id": 32,
        "question": "L2 regularization is also known as:",
        "options": ["Lasso Regression", "Ridge Regression", "Elastic Net", "Logistic Regression"],
        "answer": "Ridge Regression",
    },
    {
        "id": 33,
        "question": "What is the vanishing gradient problem?",
        "options": [
            "Gradients become too large during training",
            "Gradients approach zero, making deep network training difficult",
            "The model runs out of memory",
            "Learning rate is too high",
        ],
        "answer": "Gradients approach zero, making deep network training difficult",
    },
    {
        "id": 34,
        "question": "Which activation function helps mitigate the vanishing gradient problem?",
        "options": ["Sigmoid", "Tanh", "ReLU", "Step Function"],
        "answer": "ReLU",
    },
    {
        "id": 35,
        "question": "In a neural network, what does the backpropagation algorithm compute?",
        "options": [
            "The forward pass output",
            "Gradients of the loss with respect to weights",
            "The number of hidden layers",
            "The input features",
        ],
        "answer": "Gradients of the loss with respect to weights",
    },
    {
        "id": 36,
        "question": "Which optimizer adapts the learning rate for each parameter individually?",
        "options": ["SGD", "Batch Gradient Descent", "Adam", "Mini-batch GD"],
        "answer": "Adam",
    },
    {
        "id": 37,
        "question": "Convolutional Neural Networks (CNNs) are mainly used for:",
        "options": ["Tabular data", "Time series only", "Image data", "Graph data only"],
        "answer": "Image data",
    },
    {
        "id": 38,
        "question": "What operation does a convolutional layer perform on the input?",
        "options": ["Matrix inversion", "Element-wise addition", "Convolution (filter sliding)", "Sorting"],
        "answer": "Convolution (filter sliding)",
    },
    {
        "id": 39,
        "question": "What is the purpose of pooling layers in a CNN?",
        "options": [
            "Increase spatial dimensions",
            "Reduce spatial dimensions and computation",
            "Add more features",
            "Normalize the input",
        ],
        "answer": "Reduce spatial dimensions and computation",
    },
    {
        "id": 40,
        "question": "Recurrent Neural Networks (RNNs) are best suited for:",
        "options": ["Image classification", "Sequential / time-series data", "Dimensionality reduction", "Clustering"],
        "answer": "Sequential / time-series data",
    },
    {
        "id": 41,
        "question": "LSTM networks solve which problem of vanilla RNNs?",
        "options": [
            "Overfitting",
            "Long-term dependency / vanishing gradient",
            "High computational cost",
            "Feature scaling",
        ],
        "answer": "Long-term dependency / vanishing gradient",
    },
    {
        "id": 42,
        "question": "What does TF-IDF stand for in Natural Language Processing?",
        "options": [
            "Term Frequency - Inverse Document Frequency",
            "Text Feature - Indexed Data Format",
            "Total Frequency - Internal Data Flow",
            "Token Filter - Inverse Distance Factor",
        ],
        "answer": "Term Frequency - Inverse Document Frequency",
    },
    {
        "id": 43,
        "question": "Word2Vec converts words into:",
        "options": [
            "One-hot encoded vectors",
            "Dense numerical vectors capturing semantic meaning",
            "Binary strings",
            "Frequency tables",
        ],
        "answer": "Dense numerical vectors capturing semantic meaning",
    },
    {
        "id": 44,
        "question": "Which technique is used to handle class imbalance in a dataset?",
        "options": [
            "Increasing the learning rate",
            "SMOTE (Synthetic Minority Over-sampling Technique)",
            "Removing all minority samples",
            "Using only accuracy as a metric",
        ],
        "answer": "SMOTE (Synthetic Minority Over-sampling Technique)",
    },
    {
        "id": 45,
        "question": "Cross-validation is used to:",
        "options": [
            "Increase the dataset size",
            "Evaluate model performance more reliably on limited data",
            "Train the model faster",
            "Reduce the number of features",
        ],
        "answer": "Evaluate model performance more reliably on limited data",
    },
    {
        "id": 46,
        "question": "What is the bias-variance tradeoff?",
        "options": [
            "Choosing between accuracy and speed",
            "Balancing underfitting (high bias) and overfitting (high variance)",
            "Selecting the number of clusters",
            "Choosing between supervised and unsupervised learning",
        ],
        "answer": "Balancing underfitting (high bias) and overfitting (high variance)",
    },
    {
        "id": 47,
        "question": "Feature scaling (normalization/standardization) is important for which algorithms?",
        "options": [
            "Decision Trees only",
            "Algorithms that use distance metrics like KNN and SVM",
            "Random Forest only",
            "Naive Bayes only",
        ],
        "answer": "Algorithms that use distance metrics like KNN and SVM",
    },
    {
        "id": 48,
        "question": "Which model architecture introduced the 'Attention' mechanism that revolutionized NLP?",
        "options": ["CNN", "LSTM", "Transformer", "Autoencoder"],
        "answer": "Transformer",
    },
    {
        "id": 49,
        "question": "Transfer Learning allows you to:",
        "options": [
            "Train a model from scratch every time",
            "Reuse a pre-trained model's knowledge on a new task",
            "Transfer data between databases",
            "Convert unsupervised problems to supervised ones",
        ],
        "answer": "Reuse a pre-trained model's knowledge on a new task",
    },
    {
        "id": 50,
        "question": "GANs (Generative Adversarial Networks) consist of which two components?",
        "options": [
            "Encoder and Decoder",
            "Generator and Discriminator",
            "Tokenizer and Classifier",
            "Convolutional and Pooling layers",
        ],
        "answer": "Generator and Discriminator",
    },
]
